### ISSUE TITLE
HostAPD is not running

### ISSUE THREAD

**Issue by sumittech17** [billz/raspap-webgui#219] opened 2018-08-03 06:37 UTC
### Subject of the issue
HostAPD is not running

### Your environment
* Raspberry Pi hardware Pi 3 Model B
* RaspAP Quick Install 
* Other software or services running with RaspAP?  no

### Steps to reproduce
When I clicked on Configure hotspot --> Start

### Expected behaviour
Hotspot should be started

### Actual behaviour
HostAPD is not running
![2018-08-03 12_04_53-greenshot](https://user-images.githubusercontent.com/18280747/43627886-d676c006-9715-11e8-991d-2731bb884966.png)

**Comment by billz** [comment] 2018-08-03 07:04
Duplicate of #205 and #202. This is a known issue that will be addressed soon. Thanks

**Closed by billz** 2018-08-03 07:04 UTC
