### ISSUE TITLE
Can't able start the hotspot and run

### ISSUE THREAD

**Issue by kaskou** [billz/raspap-webgui#205] opened 2018-07-03 12:00 UTC
### Subject of the issue
Can't able start hotspot and run
environment
Pi 3 Model B+
Stretch
RasAP quick install

steps to reproduce:
Go to RasAP UI,  switch to configure wifi client, choose button rescan, and connect to the wifi network in list, configure hotspot, and start the hotspot

Expected behaviour:
able to create hotspot and run.
display the correct status of the hotspot and provide detail explanation if there is a issue.

Actual Behaviour:
can't able to create hotspot and run it

**Comment by billz** [comment] 2018-09-07 10:20
Refer to #202, thanks

**Comment by billz** [comment] 2018-09-10 09:13
Closing this as it's a duplicate of the issue referenced above.

**Closed by billz** 2018-09-10 09:13 UTC
