### ISSUE TITLE
Instructions for wlan0/wlan1 use does not work

### ISSUE THREAD

**Issue by de-mon** [billz/raspap-webgui#346] opened 2019-07-16 03:45 UTC
Managed to use up using the installer, but when I attempt to use wlan1 to connect to a wireless network via the GUI, nothing happens
Instructions provided at https://github.com/billz/raspap-webgui/wiki/FAQs#can-i-use-wlan0-and-wlan1-rather-than-eth0-for-my-ap are unclear (ie: full path to the "includes/config.php" file) and when I found the file and made the suggested changes, the expected results did no work. 

### Your environment
* Pi Zero W
* Buster lite
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* Quick-installer
* Using default configuration? Y
* Simultaneous AP and managed mode? N
* Other software or services running with RaspAP? N

### Steps to reproduce
flash Buster lite to SD card, follow update and upgrade instructions, reboot. Run quick installer, accept defaults, reboot. Follow instructions in the FAQ for https://github.com/billz/raspap-webgui/wiki/FAQs#can-i-use-wlan0-and-wlan1-rather-than-eth0-for-my-ap 

### Expected behavior
wlan0 should act as the hotspot ap (this does happen) wlan1 (an edimax or tplink usb dongle) should connect to local wifi network and traffic should pass between the two network and to clients attached to the pi access point

### Actual behavior
wlan1 unable to connect to wireless network

**Comment by billz** [comment] 2019-07-16 11:02
Duplicate of #335

**Closed by billz** 2019-07-16 11:02 UTC
