### ISSUE TITLE
It would like to run it in "bridge mode"

### ISSUE THREAD

**Issue by jmar83** [billz/raspap-webgui#400] opened 2019-09-30 00:40 UTC
It would like to run it in "bridge mode" (so no dhcp server on raspi and no different subnets)

Or is that already possible? Can't see any options for that...

Thank you for your feedbacks.

Best regards,
Jan

**Comment by jmar83** [comment] 2019-09-30 00:46
Still not available in GUI mode?
-> https://github.com/billz/raspap-webgui/issues/379

Regards, Jan

**Comment by billz** [comment] 2019-09-30 07:03
Duplicate of #379

**Closed by billz** 2019-09-30 07:03 UTC

**Comment by jmar83** [comment] 2019-10-21 13:30
ok
