### ISSUE TITLE
Can't use WLAN1 for hotspot

### ISSUE THREAD

**Issue by bmustill-rose** [billz/raspap-webgui#341] opened 2019-07-04 10:58 UTC
### Subject of the issue
I am not able to use WLAN1 to run a hotspot. The SSID is broadcast but WLAN1 shows as having an auto assigned IP address (169.254...), clients who connect don't get an IP address & manually assigning them a 10.3.141.x address doesn't work.
### Your environment
* Raspberry Pi hardware (examples: Pi 3 Model B, Pi Zero W) Pi 3 model B+
* Raspbian version (examples: Stretch Lite, Stretch Desktop) Buster Lite and Stretch Lite
* Followed the project prerequisites? (Y/N) Y
* Checked the project FAQ? (Y/N) Y
* RaspAP Quick Install or Manual setup? Quick install
* Using default configuration? (Y/N) Y
* Simultaneous AP and managed mode? (Y/N) N
* Other software or services running with RaspAP? N

### Steps to reproduce
1. Run a quick install.
2. Observe that the default configuration - E.G. Pi connected to a network through ETH0 & broadcasting the hotspot on WLAN0 works.
3. Change the interface to WLAN1 under configure hotspot.
4. Reboot.
5. Once booted attempt to connect to the Pis SSID.
### Expected behavior
Clients should be able to connect as normal - E.G. they should receive an IP address, network access should work etc.
### Actual behavior
Clients receive an auto configuration IP address and are unable to access anything.

NB: I've followed the instructions in "Can I use wlan0 and wlan1 rather than eth0 for my AP?" (although I'm not sure if they apply to my scenario) but this appears not to have had any effect. Is the ordering important?

**Comment by billz** [comment] 2019-07-04 11:48
Duplicate of #335

**Closed by billz** 2019-07-04 11:48 UTC
