### ISSUE TITLE
feature request: option for block clients

### ISSUE THREAD

**Issue by ProgrammingPlanet** [billz/raspap-webgui#717] opened 2020-11-23 18:14 UTC
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [ ] This is a bug report
* [ ] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [ ] I have read and understand the issue reporting guidelines 

**Describe the bug**

**Your environment**
* Raspberry Pi hardware (examples: Pi 3 Model B+, Pi Zero W)  
* Raspbian version (examples: Buster Lite, Buster Desktop)
* Followed the project prerequisites? (Y/N)
* Checked the project FAQ? (Y/N)
* RaspAP Quick Install or Manual setup?
* Using default configuration? (Y/N)
* Simultaneous AP and managed mode? (Y/N)
* Onboard wireless chipset or external adapter? 
* Other software or services running with RaspAP?

**Steps to reproduce**
Tell us how to reproduce this issue. Provide as much detailed information as possible.

**Expected behavior**

**Actual behavior**
Tell us what you observed instead.

**Screenshots**

**Additional context**

**Comment by billz** [comment] 2020-11-25 19:26
Duplicate of #702

**Closed by billz** 2020-11-25 19:26 UTC
Labels: duplicate
