### ISSUE TITLE
RaspAp Wifi Extender (wlan0/wlan1) issues

### ISSUE THREAD

**Issue by brunotvaz** [billz/raspap-webgui#596] opened 2020-05-28 09:51 UTC
**Before submitting an issue**
Please read this first https://github.com/billz/raspap-webgui/wiki/Reporting-issues

* [x] This is a bug report
* [x] I searched existing issues before opening this one
* [x] I checked the FAQ before creating this issue
* [x] I have read and understand the issue reporting guidelines 

**Describe the bug**
The "wireless scan" doesn't work at all. Had to change file /etc/wpa_supplicant/wpa_supplicant.conf manually

**Your environment**
* Raspberry Pi hardware: **Raspberry Pi 4**  
* Raspbian version: **Raspbian buster desktop (release 10)**
* Followed the project prerequisites? **Y**
* Checked the project FAQ? **Y**
* RaspAP Quick Install or Manual setup? **Quick (without OpenVPN)**
* Using default configuration? **Y**
* Simultaneous AP and managed mode? **N**
* Onboard wireless chipset or external adapter? **Both. On-board: Wlan0, External-USB: Wlan1 (Qualcomm Atheros Communications AR9271)**
* Other software or services running with RaspAP? **None. Default Raspbian install with Raspap only.**

**Steps to reproduce**
- Install Raspbian desktop and configure "default settings" like password etc.
- Install Raspap using "curl -sL https://install.raspap.com | bash":
       * Enable all features apart from OpenVPN
- Reboot

**Expected behavior**
I expected to see a full list of SSID's but instead the list was empty

**Actual behavior**
There were no wireless networks shown. Couldn't connect to any network

**Screenshots**

**Additional context**
I do know that it's not truly supported to have two wireless networks at this stage but I've used previous versions successfully in the past.

**Comment by brunotvaz** [comment] 2020-05-28 10:17
(additional findings)

Since I couldn't connect to any wireless network because the "scan" wasn't showing anything I decided to launch the desktop and had a look.
There I clicked the network icon and tried to configure a wireless network.
It was asking me to configure the country code (which I had before).
After choosing GB and saving the setting nothing changed. I mean it always asks for country code and won't let you pic scanned networks around you.
![wifi-country-issue](https://user-images.githubusercontent.com/1796032/83128413-4be40600-a0d3-11ea-81ec-c5392d5a6c90.PNG)

Then I decided to use raspi-config instead and it also failed to set the country code (or any wireless settings for that matter).
![raspi-config-1](https://user-images.githubusercontent.com/1796032/83128941-ffe59100-a0d3-11ea-9777-376deb351dfd.PNG)
![raspi-config-2](https://user-images.githubusercontent.com/1796032/83128960-096ef900-a0d4-11ea-9e56-7dba8acfdeb2.PNG)
![raspi-config-3](https://user-images.githubusercontent.com/1796032/83128970-0e33ad00-a0d4-11ea-9e3d-9a634ec4440e.PNG)

![raspi-config-4](https://user-images.githubusercontent.com/1796032/83128980-112e9d80-a0d4-11ea-9941-4eb0b856cd25.PNG)
![raspi-config-5](https://user-images.githubusercontent.com/1796032/83128986-1390f780-a0d4-11ea-9154-09e4313922f4.PNG)
![raspi-config-6](https://user-images.githubusercontent.com/1796032/83128990-168be800-a0d4-11ea-9950-c1aed5c1f18f.PNG)

The only way I could get my wireless networks working was by changing manually the file:
**/etc/wpa_supplicant/wpa_supplicant.conf**
`ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=GB

network={
        ssid="my_private_wireless_1"
        psk="my_private_wireless_1_passcode"
        key_mgmt=WPA-PSK
}

network={
	ssid="my_private_wireless_2"
	psk="my_private_wireless_2_passcode"
}
`

**Comment by brunotvaz** [comment] 2020-05-28 11:11
So... after configuring the wireless networks manually I still didn't had any internet access.
Since I'm not using eth1, I'm guessing the reason is to due with the "hard coded" settings of the RaspAp application.
I mean, my network settings were like:
![raspap-eth0](https://user-images.githubusercontent.com/1796032/83134098-c3b62e80-a0db-11ea-9dac-9456cdbeffe9.PNG)
![raspap-wlan0](https://user-images.githubusercontent.com/1796032/83134121-cb75d300-a0db-11ea-8812-55ce97758608.PNG)
![raspap-wlan1](https://user-images.githubusercontent.com/1796032/83134134-d0d31d80-a0db-11ea-8e4c-215022dc684b.PNG)
That would never work for me because eth0 was not plugged in and also my "internet network" was wlan1 instead of the "hard coded" eth0 default gateway" setting.

**Comment by brunotvaz** [comment] 2020-05-28 11:23
To make it work (in my scenario) I had to do the following steps:
![raspbian_network_settings](https://user-images.githubusercontent.com/1796032/83135309-8d79ae80-a0dd-11ea-9242-0f1b28ad40de.png)
![raspbian_network_settings_eth0](https://user-images.githubusercontent.com/1796032/83135321-923e6280-a0dd-11ea-91e6-a80489a2785d.png)
![raspbian_network_settings_wlan0](https://user-images.githubusercontent.com/1796032/83135330-94a0bc80-a0dd-11ea-925b-2f70508d9876.png)
![raspbian_network_settings_wlan1](https://user-images.githubusercontent.com/1796032/83135342-979bad00-a0dd-11ea-8ccd-fe06414f4e23.png)

With those settings I've managed to enable internet access via the eth0 network and therefore all devices in that network (192.168.2.xxx) have internet access.

**NOTE: I cannot use the Raspap "save" options because it breaks the above configurations back to the "hard coded settings".**

**Comment by brunotvaz** [comment] 2020-05-28 11:45
Summary:

I have it working at the moment but it's extremely limited. I cannot:
- Scan for wireless networks
- Change "networking" settings using the RaspAp app because it defaults to the "eth0 scenario"
- Change "hotspot" settings using the RaspAp app because it defaults to the "eth0 scenario"
- Change "dhcp server" settings using the RaspAp app because it defaults to the "eth0 scenario"

If I may can I suggest a couple of things?
**- Have the RaspAp installer ask which IP to use for the hotspot instead of the "hard coded" 10.3.141.1 by default.
- Have the RaspAp installer ask which is the "internet gateway interface"  instead of assuming eth0 or prevent hard coded values altogether** 
I have read the following: #https://github.com/billz/raspap-webgui/issues/580 and it seems that findings are somehow correct. There are "hard coded values" that break the app if not using the "default eth0/wlan0 scenario".

I'm sorry for the long post(s). Just trying to help @billz and the community as much as I can.

**Comment by billz** [comment] 2020-05-29 09:02
Refer to [this FAQ](https://github.com/billz/raspap-webgui/wiki/FAQs#wifi-scanning-doesnt-work-or-i-get-the-error-cannot-execute-wpa_cli-reconfigure-help) which addresses this.

The issue with wpa_supplicant is specific to Raspbian; other Debian-based distros do not exhibit this problem. I have not had time to dig into the root cause and would rather not build in a 
workaround for a poor implementation. For now, it's a manual fix as described in the FAQ.

The FAQ also explains why configurations with external adapters are unsupported.

Changing the default config at install time is unlikely to happen. The vast majority of RaspAP's users want to get a working AP up quickly with a 'known good' base config that can then be modified via the UI. This is a guiding principle of the project. Changing the network config at install time invites potential conflicts which leads to more troubleshooting, bug reports, etc. The harsh reality is I don't have time for this.

Anyway, welcome!

**Comment by billz** [comment] 2020-06-09 10:40
To the core issue re: wlan0/wlan1, this should be resolved with #582.

**Closed by billz** 2020-06-09 10:40 UTC
Labels: read the faq
