### ISSUE TITLE
Quick Instal error

### ISSUE THREAD

**Issue by helloxx666** [billz/raspap-webgui#344] opened 2019-07-10 02:59 UTC
* Raspberry Pi hardware ： Pi 3 Model B+
* Raspbian version ：Raspbian Buster with desktop and recommended software
* Followed the project prerequisites? Y
* Checked the project FAQ? Y
* RaspAP Quick Install

Hi
I try install RaspAP by：
wget -q https://git.io/voEUQ -O /tmp/raspap && bash /tmp/raspap

Output：
RaspAP Install: Updating sources
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
RaspAP Install Error: Unable to update package list

I try “”sudo apt-get --allow-releaseinfo-change update”。The same problem
pi@raspberrypi:~ $ sudo apt-get --allow-releaseinfo-change update
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options

how to solve this problem?
Thanks!

**Comment by billz** [comment] 2019-07-10 06:43
Duplicate of #343

**Closed by billz** 2019-07-10 06:43 UTC
